### ISSUE TITLE
Decode params

### ISSUE THREAD

**Issue by rahatarmanahmed** [yoshuawuyts/sheet-router#70]
Does it make sense to automatically decode params with `decodeURIComponent`? I've run into a situation where I need characters like `#` in one of my params. Right now I'm just wrapping the route handler to convert it manually. I'm wondering if there are downsides to doing it automatically in sheet-router, though.

**Comment by rahatarmanahmed** [comment]
I just noticed #63, and it looks like we are decoding query strings, so I think this is something we want. I'll try to get a PR for this.

**Comment by rahatarmanahmed** [comment]
😓

[This was my attempt at doing this](https://github.com/rahatarmanahmed/sheet-router/commit/98b4bf18c868bf9ab88e60775b7be36937ac3986). But the tests made me realize this would break if a user used sheet-router/walk over the router and used a function that didn't pass in the params.

I think this might have to be done in `wayfarer`, but url decoding doesn't seem appropriate to put there. I'm not sure how to solve this within sheet-router, maybe i'm missing something obvious.

**Comment by yoshuawuyts** [comment]
Yeah decoding params seems reasonable (:

**Comment by jekrb** [comment]
Not sure if this will fix an issue I've just ran into?  If I'm using hash routing and need to grab a querystring on page load, it seems the router thinks I'm going to `/` instead of `#my/route`.

I think this is because the full path is `localhost:8080/?param=value#my/route` where the expected behavior is to route to the hash.

The routing works fine if I put the querystring _after_ the hash, but then `querystring` in node core and browserify thinks the query param is `{localhost:8080/#my/route?param: 'value'}` rather than `{param: 'value'}`.

Does this make sense?  I can work around this for now and unpack it further in a new a issue thread if needed.

**Comment by rahatarmanahmed** [comment]
I don't think so, the PR I made in wayfarer just runs the already parsed params thru `decodeURIComponent()`: https://github.com/yoshuawuyts/wayfarer/pull/51/files

Maybe best to open another issue with an example.

(also the hash is supposed to come after the query string in a valid url)

**Comment by jekrb** [comment]
Yeah my issue is that hash after the querystring isn't routing properly.

I'm build a project in choo and just ran into this.  I don't have much time at the moment to write a minimally reproducible case at the moment - perhaps next weekend I'll have some more time to maybe right a test for this sheet-router.

**Comment by rahatarmanahmed** [comment]
Fixed in https://github.com/yoshuawuyts/wayfarer/pull/51
