### ISSUE TITLE
Using thunks returns null

### ISSUE THREAD

**Issue by kvnneff** [yoshuawuyts/sheet-router#9]
Whenever I attempt to use `thunk` over `route` with sheet-router `null` gets returned rather than a vnode.  I didn't see any tests using the thunk option, is this confirmed to be working or am I not using it correctly?

I made a requirebin to demonstrate: http://requirebin.com/?gist=058decac3c6efe06454a

**Comment by yoshuawuyts** [comment]
Interesting, this shouldn't be happening - investigating

**Comment by yoshuawuyts** [comment]
So what `thunk` does is decouple the `path` matching from the dom node being returned. It's got a signature of:
```txt
(string) -> (obj, ...any) -> any
```
the regular router path has a signature of:
```txt
(string, obj, ...any) -> any
````

The reason of doing this is because state changes can happen up to 60 times a second, whereas path changes are a lot less common. By using a thunk this can be optimized by doing a very cheap `previousPath === newPath` check to determine if the routing tree should be traversed or not. [`bridge.js`](https://github.com/yoshuawuyts/sheet-router/blob/master/bridge.js) has an implementation that provides this check.

So to fix your example, change line 13 to:
```js
const node = render(router('/foo/bar')(h, { name: 'Jane' }))
```

I agree the documentation is a bit shoddy, and `s`, `t` as arguments can be a bit confusing - if you've got a good idea on how to make this a smoother experience I'd be keen to hear!

I hope this answers your question! Cheers :sparkles:
